"""UX Design Flow — 7-step autodev simplification of BMAD's 14-step workflow.

Steps (deterministic, no LLM by default):
  1. discovery         — extract user personas + core use-cases from PRD
  2. core-experience   — define primary user journey
  3. design-system     — colour palette + typography + spacing tokens (JSON)
  4. component-strategy— list components per primary use cases
  5. ux-patterns       — select UX patterns
  6. responsive-a11y   — breakpoints + accessibility checks
  7. complete          — assemble UXDesignSpec, write product/ux_design.md
"""
from __future__ import annotations

from pathlib import Path

from ..agents.ux_designer import (
    _DEFAULT_A11Y,
    _DEFAULT_BREAKPOINTS,
    _DEFAULT_TOKENS,
    UXDesignerAgent,
    _default_components,
    _default_journey,
    _default_patterns,
    _default_personas,
    _resolve_product_name,
)
from ..schemas import (
    PRD,
    UXDesignInput,
    UXDesignSpec,
)


class UXDesignFlow:
    """Run BMAD-Sally's 7-step UX design process in-process (no LLM by default)."""

    def __init__(self, *, use_llm: bool = False) -> None:
        self._agent = UXDesignerAgent(use_llm=use_llm)

    # ------------------------------------------------------------------
    # Main entry point
    # ------------------------------------------------------------------

    def run(self, inputs: UXDesignInput) -> UXDesignSpec:
        """Execute all 7 steps and return a populated UXDesignSpec."""
        prd = inputs.prd
        brief = inputs.product_brief
        product_name = inputs.product_name or _resolve_product_name(prd, brief)

        # Step 1 — discovery
        personas = self._step_discovery(product_name, prd)

        # Step 2 — core-experience
        journeys = self._step_core_experience(product_name, personas)

        # Step 3 — design-system
        tokens = self._step_design_system()

        # Step 4 — component-strategy
        components = self._step_component_strategy(prd)

        # Step 5 — ux-patterns
        patterns = self._step_ux_patterns(prd)

        # Step 6 — responsive-a11y
        breakpoints, a11y_checks = self._step_responsive_a11y()

        # Step 7 — complete (assemble + write)
        spec = self._step_complete(
            product_name=product_name,
            personas=personas,
            journeys=journeys,
            tokens=tokens,
            components=components,
            patterns=patterns,
            breakpoints=breakpoints,
            a11y_checks=a11y_checks,
            repo_path=inputs.repo_path,
        )
        return spec

    # ------------------------------------------------------------------
    # Individual steps
    # ------------------------------------------------------------------

    def _step_discovery(self, product_name: str, prd: PRD | None):
        """Step 1: extract user personas + core use-cases from PRD."""
        return _default_personas(product_name, prd)

    def _step_core_experience(self, product_name: str, personas):
        """Step 2: define primary user journey for the lead persona."""
        if not personas:
            return []
        return [_default_journey(product_name, personas[0])]

    def _step_design_system(self):
        """Step 3: color palette + typography + spacing design tokens."""
        return list(_DEFAULT_TOKENS)

    def _step_component_strategy(self, prd: PRD | None):
        """Step 4: determine component set from PRD requirements."""
        return _default_components(prd)

    def _step_ux_patterns(self, prd: PRD | None):
        """Step 5: select UX patterns appropriate for the product."""
        return _default_patterns(prd)

    def _step_responsive_a11y(self):
        """Step 6: set responsive breakpoints and accessibility checks."""
        return list(_DEFAULT_BREAKPOINTS), list(_DEFAULT_A11Y)

    def _step_complete(
        self,
        *,
        product_name: str,
        personas,
        journeys,
        tokens,
        components,
        patterns,
        breakpoints,
        a11y_checks,
        repo_path: str,
    ) -> UXDesignSpec:
        """Step 7: assemble full UXDesignSpec and write product/ux_design.md."""
        spec = UXDesignSpec(
            product_name=product_name,
            personas=personas,
            journeys=journeys,
            design_tokens=tokens,
            components=components,
            patterns=patterns,
            breakpoints=breakpoints,
            a11y_checks=a11y_checks,
            notes=[
                "Generated by UXDesignFlow (BMAD-8 / Sally) — 7-step deterministic mode.",
                "Replace with LLM-driven mode by constructing UXDesignFlow(use_llm=True).",
            ],
        )

        # Write output file
        self._write_spec(spec, repo_path)
        return spec

    # ------------------------------------------------------------------
    # Output
    # ------------------------------------------------------------------

    def _write_spec(self, spec: UXDesignSpec, repo_path: str) -> None:
        """Write product/ux_design.md to the repo product directory."""
        out_dir = Path(repo_path) / "product"
        out_dir.mkdir(parents=True, exist_ok=True)
        out_path = out_dir / "ux_design.md"
        markdown = self._agent.render_markdown(spec)
        out_path.write_text(markdown, encoding="utf-8")
