#!/usr/bin/env bash
# refresh-resources.sh — Re-fetch Homebrew resource blocks for autodev-x's runtime deps.
# Run this whenever you update dependencies or cut a new release.
# Output is printed to stdout; paste it into Formula/autodev-x.rb to replace resource blocks.
#
# Usage:
#   ./packaging/homebrew/refresh-resources.sh
#   ./packaging/homebrew/refresh-resources.sh pydantic typer rich   # subset of deps
#
# Requirements: curl, python3 (or jq as fallback for JSON parsing)

set -euo pipefail

DEPS=("pydantic" "typer" "rich" "PyYAML" "jinja2" "click" "mdurl" "markdown-it-py" "pygments" "shellingham")

# Allow caller to override the dep list via positional args
if [[ $# -gt 0 ]]; then
  DEPS=("$@")
fi

# Prefer homebrew-pypi-poet if available (produces complete resource blocks automatically)
if command -v poet &>/dev/null; then
  echo "# Generated by homebrew-pypi-poet"
  poet --resources "${DEPS[@]}"
  exit 0
fi

# Fallback: manual PyPI JSON API lookup
echo "# Generated by refresh-resources.sh (manual PyPI lookup)"
echo "# Replace the resource blocks in Formula/autodev-x.rb with the output below."
echo ""

for pkg in "${DEPS[@]}"; do
  # PyPI API is case-insensitive but normalises the package name
  json=$(curl -sf --max-time 30 "https://pypi.org/pypi/${pkg}/json") || {
    echo "  # TODO: could not fetch ${pkg} from PyPI — update sha256 manually" 1>&2
    printf '  resource "%s" do\n    url "# TODO"\n    sha256 "# TODO"\n  end\n\n' "$pkg"
    continue
  }

  # Parse with python3 (always available on macOS)
  echo "$json" | python3 - "$pkg" <<'PYEOF'
import json, sys

pkg = sys.argv[1]
# Read JSON from stdin
d = json.load(sys.stdin)
v = d["info"]["version"]
files = d["releases"][v]

# Prefer sdist, then pure wheel, then anything
sdist  = [f for f in files if f["filename"].endswith(".tar.gz")]
wheel  = [f for f in files if f["filename"].endswith("-none-any.whl")]
chosen = (sdist or wheel or files)[0]

print(f'  resource "{pkg}" do')
print(f'    url "{chosen["url"]}"')
print(f'    sha256 "{chosen["digests"]["sha256"]}"')
print(f'  end')
print()
PYEOF
done
