"""DocSharder: split large markdown docs by H2/H3 into separate shard files.

Trigger: >3000 chars (configurable). Idempotent — safe to re-run.
"""
from __future__ import annotations

import re
from pathlib import Path

from ..schemas import ShardEntry, ShardingReport

_HEADING_RE = re.compile(r"^(#{2,3})\s+(.+)$", re.MULTILINE)
_SLUG_RE = re.compile(r"[^a-z0-9]+")


def _slugify(title: str) -> str:
    return _SLUG_RE.sub("-", title.lower()).strip("-")[:60]


def _parse_sections(
    text: str,
) -> list[tuple[int, str, str]]:
    """Return list of (level, title, body) tuples for each H2/H3 section.

    The preamble before the first heading is returned as level=0, title="".
    """
    matches = list(_HEADING_RE.finditer(text))
    if not matches:
        return [(0, "", text)]

    sections: list[tuple[int, str, str]] = []
    preamble_end = matches[0].start()
    preamble = text[:preamble_end]
    if preamble.strip():
        sections.append((0, "", preamble))

    for i, m in enumerate(matches):
        level = len(m.group(1))
        title = m.group(2).strip()
        body_start = m.end() + 1  # skip the newline after heading
        body_end = matches[i + 1].start() if i + 1 < len(matches) else len(text)
        body = text[body_start:body_end].rstrip()
        sections.append((level, title, body))

    return sections


class DocSharder:
    """Split large markdown documents into per-section shard files."""

    def __init__(self, threshold: int = 3000) -> None:
        self.threshold = threshold

    def shard(
        self,
        markdown_text: str,
        target_dir: Path,
        base_name: str = "doc",
    ) -> ShardingReport:
        """Split *markdown_text* into shards if it exceeds the threshold.

        Parameters
        ----------
        markdown_text:
            Raw markdown content to potentially shard.
        target_dir:
            Directory where the TOC file and shard sub-directory are written.
        base_name:
            Base filename; TOC → ``{target_dir}/{base_name}.md``,
            shards → ``{target_dir}/{base_name}/{NN-slug}.md``.

        Returns
        -------
        ShardingReport
            Describes what was written (or skipped if under threshold).
        """
        source_chars = len(markdown_text)

        if source_chars <= self.threshold:
            return ShardingReport(source_chars=source_chars, sharded=False)

        sections = _parse_sections(markdown_text)
        heading_sections = [(lv, t, b) for lv, t, b in sections if lv >= 2]

        if not heading_sections:
            # No H2/H3 — nothing to shard
            return ShardingReport(source_chars=source_chars, sharded=False)

        target_dir = Path(target_dir)
        shard_dir = target_dir / base_name
        shard_dir.mkdir(parents=True, exist_ok=True)

        shard_entries: list[ShardEntry] = []
        toc_lines: list[str] = []
        toc_lines.append(f"# {base_name} — Table of Contents\n")
        toc_lines.append(
            "_Auto-generated by DocSharder. Edit source doc, not shards directly._\n"
        )

        # Write preamble sections into TOC directly
        for lv, _title, body in sections:
            if lv == 0 and body.strip():
                toc_lines.append(body.strip())
                toc_lines.append("")

        counter = 0
        for lv, title, body in sections:
            if lv < 2:
                continue
            counter += 1
            slug = _slugify(title)
            shard_filename = f"{counter:02d}-{slug}.md"
            shard_path = shard_dir / shard_filename

            heading_prefix = "#" * lv
            shard_content = f"{heading_prefix} {title}\n\n{body}\n"
            shard_path.write_text(shard_content, encoding="utf-8")

            rel_path = f"{base_name}/{shard_filename}"
            indent = "  " * (lv - 2)
            toc_lines.append(f"{indent}- [{title}]({rel_path})")

            shard_entries.append(
                ShardEntry(
                    path=str(shard_path),
                    title=title,
                    level=lv,
                    char_count=len(shard_content),
                )
            )

        toc_lines.append("")
        toc_text = "\n".join(toc_lines)
        toc_path = target_dir / f"{base_name}.md"
        toc_path.write_text(toc_text, encoding="utf-8")

        return ShardingReport(
            source_chars=source_chars,
            sharded=True,
            shard_count=len(shard_entries),
            toc_path=str(toc_path),
            shards=shard_entries,
        )
