"""Tests for the richer Python scaffold layout generated by ScaffolderAgent."""
from __future__ import annotations

import pytest

from autodev.agents.scaffolder import ScaffolderAgent
from autodev.schemas import Language, PipelineMode


@pytest.fixture()
def agent() -> ScaffolderAgent:
    return ScaffolderAgent()


@pytest.fixture()
def plan(agent):
    return agent.plan(project_name="mytools", languages=[Language.PYTHON])


@pytest.fixture()
def applied(tmp_path, agent, plan):
    agent.apply(plan=plan, repo_path=str(tmp_path), mode=PipelineMode.APPLY)
    return tmp_path


# 1) pyproject.toml contains [project.scripts] with correct pkg.cli:main entry
def test_pyproject_contains_console_script(applied):
    content = (applied / "pyproject.toml").read_text()
    assert 'mytools = "mytools.cli:main"' in content


# 2) src/{pkg}/__init__.py imports main from .cli
def test_pkg_init_imports_main(applied):
    content = (applied / "src" / "mytools" / "__init__.py").read_text()
    assert "from .cli import main" in content
    assert "__all__" in content


# 3) src/{pkg}/cli.py has def main(argv signature and raises NotImplementedError
def test_pkg_cli_has_main_and_not_implemented(applied):
    content = (applied / "src" / "mytools" / "cli.py").read_text()
    assert "def main(argv" in content
    assert "NotImplementedError" in content


# 4) src/{pkg}/core.py exists and contains only docstring (empty-ish)
def test_pkg_core_exists_docstring_only(applied):
    core = applied / "src" / "mytools" / "core.py"
    assert core.exists()
    content = core.read_text().strip()
    # Should have a docstring but no real class/function definitions
    assert '"""' in content
    assert "def " not in content
    assert "class " not in content


# 5) tests/test_smoke.py imports {pkg}.cli
def test_smoke_test_imports_cli(applied):
    content = (applied / "tests" / "test_smoke.py").read_text()
    assert "from mytools.cli import main" in content


# 6) apply is idempotent — cli.py not overwritten on second apply
def test_apply_idempotent_cli_not_overwritten(tmp_path, agent, plan):
    agent.apply(plan=plan, repo_path=str(tmp_path), mode=PipelineMode.APPLY)
    cli_path = tmp_path / "src" / "mytools" / "cli.py"
    original = cli_path.read_text()
    marker = "# MODIFIED\n"
    cli_path.write_text(marker + original)
    agent.apply(plan=plan, repo_path=str(tmp_path), mode=PipelineMode.APPLY)
    assert cli_path.read_text().startswith(marker), "Second apply must not overwrite cli.py"


# 7) hyphenated project name produces valid Python slug
def test_hyphenated_project_name_slug(tmp_path, agent):
    plan = agent.plan(project_name="my-project", languages=[Language.PYTHON])
    agent.apply(plan=plan, repo_path=str(tmp_path), mode=PipelineMode.APPLY)
    assert (tmp_path / "src" / "my_project" / "cli.py").exists()
    content = (tmp_path / "pyproject.toml").read_text()
    assert 'my_project = "my_project.cli:main"' in content
